package RecommendationView;

import RecommendationController.RecommendationController;
import java.awt.Color;
import javax.swing.JPanel;

public class RecommendationView extends javax.swing.JFrame {
    private RecommendationController rc;
    //Different Panels for moods
    private HappyRecommendationsPanel happyPanel;
    private ExcitedRecommendationsPanel excitedPanel;
    private RelaxedRecommendationsPanel relaxedPanel;
    private ActiveRecommendationsPanel activePanel;
    
    
    public RecommendationView(RecommendationController r) {
        rc = r;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recommendationsPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        notificationsButton = new javax.swing.JButton();
        viewUserButton = new javax.swing.JButton();
        splitterTopFromBottom = new javax.swing.JSeparator();
        presentingLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        goToChartButton = new javax.swing.JButton();
        goToFoodMoodButton = new javax.swing.JButton();
        goToRecommButton = new javax.swing.JButton();
        happyMoodButton = new javax.swing.JButton();
        activeMoodButton = new javax.swing.JButton();
        relaxedMoodButton = new javax.swing.JButton();
        excitedMoodButton = new javax.swing.JButton();
        goodMoodLabel = new javax.swing.JLabel();
        relaxedMoodLabel = new javax.swing.JLabel();
        excitedMoodLabel = new javax.swing.JLabel();
        activeMoodLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        recommendationsPanel.setBackground(new java.awt.Color(255, 255, 255));
        recommendationsPanel.setPreferredSize(new java.awt.Dimension(375, 667));
        recommendationsPanel.setSize(new java.awt.Dimension(375, 667));
        recommendationsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                recommendationsPanelMousePressed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        titleLabel.setText("FoodMood");

        notificationsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alarm.png"))); // NOI18N
        notificationsButton.setPreferredSize(new java.awt.Dimension(30, 38));
        notificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsButtonActionPerformed(evt);
            }
        });

        viewUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crud_user_lines.png"))); // NOI18N

        splitterTopFromBottom.setForeground(new java.awt.Color(51, 51, 51));

        presentingLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        presentingLabel.setText("How do you want to feel?");

        footerPanel.setBackground(new java.awt.Color(102, 102, 102));
        footerPanel.setPreferredSize(new java.awt.Dimension(375, 56));

        goToChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pie-chart.png"))); // NOI18N
        goToChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToChartButtonActionPerformed(evt);
            }
        });

        goToFoodMoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cutlery_1.png"))); // NOI18N
        goToFoodMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFoodMoodButtonActionPerformed(evt);
            }
        });

        goToRecommButton.setBackground(new java.awt.Color(204, 204, 204));
        goToRecommButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/recommended.png"))); // NOI18N

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(goToChartButton)
                .addGap(54, 54, 54)
                .addComponent(goToFoodMoodButton)
                .addGap(54, 54, 54)
                .addComponent(goToRecommButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goToChartButton)
                    .addComponent(goToFoodMoodButton)
                    .addComponent(goToRecommButton))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        happyMoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/good.png"))); // NOI18N
        happyMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                happyMoodButtonActionPerformed(evt);
            }
        });

        activeMoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alert.png"))); // NOI18N
        activeMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeMoodButtonActionPerformed(evt);
            }
        });

        relaxedMoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/relaxed.png"))); // NOI18N
        relaxedMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relaxedMoodButtonActionPerformed(evt);
            }
        });

        excitedMoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excited.png"))); // NOI18N
        excitedMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excitedMoodButtonActionPerformed(evt);
            }
        });

        goodMoodLabel.setText("Happy");

        relaxedMoodLabel.setText("Relaxed");

        excitedMoodLabel.setText("Excited");

        activeMoodLabel.setText("Active");

        javax.swing.GroupLayout recommendationsPanelLayout = new javax.swing.GroupLayout(recommendationsPanel);
        recommendationsPanel.setLayout(recommendationsPanelLayout);
        recommendationsPanelLayout.setHorizontalGroup(
            recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitterTopFromBottom)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
            .addGroup(recommendationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(notificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recommendationsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(presentingLabel)
                .addGap(75, 75, 75))
            .addGroup(recommendationsPanelLayout.createSequentialGroup()
                .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recommendationsPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(happyMoodButton)
                            .addComponent(excitedMoodButton))
                        .addGap(37, 37, 37)
                        .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activeMoodButton)
                            .addComponent(relaxedMoodButton)))
                    .addGroup(recommendationsPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(goodMoodLabel)
                        .addGap(94, 94, 94)
                        .addComponent(relaxedMoodLabel))
                    .addGroup(recommendationsPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(excitedMoodLabel)
                        .addGap(90, 90, 90)
                        .addComponent(activeMoodLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recommendationsPanelLayout.setVerticalGroup(
            recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendationsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel)
                    .addComponent(notificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitterTopFromBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(presentingLabel)
                .addGap(48, 48, 48)
                .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(happyMoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(relaxedMoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goodMoodLabel)
                    .addComponent(relaxedMoodLabel))
                .addGap(35, 35, 35)
                .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excitedMoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activeMoodButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recommendationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excitedMoodLabel)
                    .addComponent(activeMoodLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recommendationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recommendationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsButtonActionPerformed
        rc.toNotificationCntrl();
        this.setVisible(false);
    }//GEN-LAST:event_notificationsButtonActionPerformed

    private void recommendationsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendationsPanelMousePressed

    }//GEN-LAST:event_recommendationsPanelMousePressed

    private void goToFoodMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFoodMoodButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_goToFoodMoodButtonActionPerformed

    private void goToChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToChartButtonActionPerformed
        rc.toStatsCntrl();
        this.setVisible(false);
    }//GEN-LAST:event_goToChartButtonActionPerformed

    private void happyMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_happyMoodButtonActionPerformed
        happyPanel = new HappyRecommendationsPanel(rc);
        settingUpMoodRecommendedPanels(happyPanel);
    }//GEN-LAST:event_happyMoodButtonActionPerformed

    private void relaxedMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relaxedMoodButtonActionPerformed
        relaxedPanel = new RelaxedRecommendationsPanel(rc);
        settingUpMoodRecommendedPanels(relaxedPanel);
    }//GEN-LAST:event_relaxedMoodButtonActionPerformed

    private void excitedMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excitedMoodButtonActionPerformed
        excitedPanel = new ExcitedRecommendationsPanel(rc);
        settingUpMoodRecommendedPanels(excitedPanel);
    }//GEN-LAST:event_excitedMoodButtonActionPerformed

    private void activeMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeMoodButtonActionPerformed
        activePanel = new ActiveRecommendationsPanel(rc);
        settingUpMoodRecommendedPanels(activePanel);
    }//GEN-LAST:event_activeMoodButtonActionPerformed
    
    /**
     * This class is using the containerForFrame object that is in RecommendationController
     * The change is being done in this class
     * @param gettingPanelToAdd 
     */
    public void settingUpMoodRecommendedPanels(JPanel gettingPanelToAdd){
        rc.setContainerForPanels(new FoodMoodRecommendationContainer());
        rc.getContainerForPanels().setVisible(true);        
        rc.getContainerForPanels().setContentPane(gettingPanelToAdd);
        rc.getContainerForPanels().revalidate();
        rc.getContainerForPanels().repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activeMoodButton;
    private javax.swing.JLabel activeMoodLabel;
    private javax.swing.JButton excitedMoodButton;
    private javax.swing.JLabel excitedMoodLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JButton goToChartButton;
    private javax.swing.JButton goToFoodMoodButton;
    private javax.swing.JButton goToRecommButton;
    private javax.swing.JLabel goodMoodLabel;
    private javax.swing.JButton happyMoodButton;
    private javax.swing.JButton notificationsButton;
    private javax.swing.JLabel presentingLabel;
    private javax.swing.JPanel recommendationsPanel;
    private javax.swing.JButton relaxedMoodButton;
    private javax.swing.JLabel relaxedMoodLabel;
    private javax.swing.JSeparator splitterTopFromBottom;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewUserButton;
    // End of variables declaration//GEN-END:variables
}
