package MainMenu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 * This class represent a single FoodMood entry card
 * These cars will be added as the user chooses to do so
 * @author Akhil
 */
public class FoodMoodCardsPanel extends javax.swing.JPanel {
    private MainMenuController mmc;
    private String food, mood;
    
    
    /**
     * Creates new form FoodMoodCardsPanel
     */
    public FoodMoodCardsPanel(MainMenuController mmc) {
        this.mmc = mmc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstEntryFoodMood = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        foodLabel = new javax.swing.JLabel();
        moodLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateShownLabel = new javax.swing.JLabel();
        foodEnterByUser = new javax.swing.JTextField();
        moodEnterByUser = new javax.swing.JTextField();

        setSize(new java.awt.Dimension(335, 113));

        firstEntryFoodMood.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        deleteButton.setText("Delete");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        foodLabel.setText("Food:");

        moodLabel.setText("Mood:");

        dateLabel.setText("Date:");

        dateShownLabel.setText("");
        //tickTock();
        //
        //Timer timer = new Timer(500, new ActionListener() {
            //    @Override
            //    public void actionPerformed(ActionEvent e) {
                //        tickTock();
                //    }
            //});
    //timer.setRepeats(true);
    //timer.setCoalesce(true);
    //timer.setInitialDelay(0);
    //timer.start();

    foodEnterByUser.setText(mmc.getMainMenuUI().foodTextFieldToString());
    foodEnterByUser.setEnabled(false);

    moodEnterByUser.setText(mmc.getMainMenuUI().moodTextFieldToString());
    moodEnterByUser.setEnabled(false);

    javax.swing.GroupLayout firstEntryFoodMoodLayout = new javax.swing.GroupLayout(firstEntryFoodMood);
    firstEntryFoodMood.setLayout(firstEntryFoodMoodLayout);
    firstEntryFoodMoodLayout.setHorizontalGroup(
        firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
                    .addComponent(moodLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(moodEnterByUser))
                .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
                    .addComponent(foodLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(foodEnterByUser, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
                    .addComponent(dateLabel)
                    .addGap(18, 18, 18)
                    .addComponent(dateShownLabel)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addGroup(firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(40, 40, 40))
    );
    firstEntryFoodMoodLayout.setVerticalGroup(
        firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(foodLabel)
                .addComponent(foodEnterByUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editButton))
            .addGroup(firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moodLabel)
                        .addComponent(moodEnterByUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(firstEntryFoodMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateShownLabel)
                        .addComponent(dateLabel)))
                .addGroup(firstEntryFoodMoodLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(deleteButton)))
            .addGap(25, 25, 25))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(firstEntryFoodMood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(firstEntryFoodMood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if(editButton.getText().equals("Edit")){
            editButton.setText("Save");
            foodEnterByUser.enable(true);
            moodEnterByUser.enable(true);
        }
        else{
            editButton.setText("Edit");
            foodEnterByUser.enable(false);
            moodEnterByUser.enable(false);
        }
        
    }//GEN-LAST:event_editButtonActionPerformed
    
    public void tickTock(){
        dateShownLabel.setText(DateFormat.getDateTimeInstance().format(new Date()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateShownLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel firstEntryFoodMood;
    private javax.swing.JTextField foodEnterByUser;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JTextField moodEnterByUser;
    private javax.swing.JLabel moodLabel;
    // End of variables declaration//GEN-END:variables
}
