package MainMenu;

import RecommendationController.RecommendationController;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.MatteBorder;

public class MainMenuUI extends javax.swing.JFrame {
    private MainMenuController mmc;
    private FoodMoodCardsPanel addANewFoodMood;
    private String food, mood;
    
    /**
     * Creates new form MainMenuUI
     */
    public MainMenuUI(MainMenuController mmc) {
        this.mmc = mmc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mainMenuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        notificationsButton = new javax.swing.JButton();
        viewUserButton = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();
        goToChartButton = new javax.swing.JButton();
        goToFoodMoodButton = new javax.swing.JButton();
        goToRecommButton = new javax.swing.JButton();
        foodEnterField = new javax.swing.JTextField();
        moodEnterField = new javax.swing.JTextField();
        addFoodMoodButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        newScrollPane = new javax.swing.JScrollPane();
        backgroundPanel = new javax.swing.JPanel(new GridBagLayout());

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FoodMood - Main Menu");
        setResizable(false);

        mainMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(375, 667));

        titleLabel.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        titleLabel.setText("FoodMood");

        notificationsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alarm.png"))); // NOI18N
        notificationsButton.setPreferredSize(new java.awt.Dimension(30, 38));
        notificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsButtonActionPerformed(evt);
            }
        });

        viewUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crud_user_lines.png"))); // NOI18N

        footerPanel.setBackground(new java.awt.Color(102, 102, 102));
        footerPanel.setPreferredSize(new java.awt.Dimension(375, 56));

        goToChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pie-chart.png"))); // NOI18N
        goToChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToChartButtonActionPerformed(evt);
            }
        });

        goToFoodMoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cutlery_1.png"))); // NOI18N

        goToRecommButton.setBackground(new java.awt.Color(204, 204, 204));
        goToRecommButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/recommended.png"))); // NOI18N
        goToRecommButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRecommButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(goToChartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goToFoodMoodButton)
                .addGap(77, 77, 77)
                .addComponent(goToRecommButton)
                .addGap(38, 38, 38))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goToChartButton)
                    .addComponent(goToFoodMoodButton)
                    .addComponent(goToRecommButton))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        foodEnterField.setBackground(new java.awt.Color(204, 204, 204));
        foodEnterField.setText("What you ate");
        foodEnterField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                foodEnterFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                foodEnterFieldFocusLost(evt);
            }
        });

        moodEnterField.setBackground(new java.awt.Color(204, 204, 204));
        moodEnterField.setText("How you feel");
        moodEnterField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                moodEnterFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                moodEnterFieldFocusLost(evt);
            }
        });

        addFoodMoodButton.setBackground(new java.awt.Color(204, 102, 0));
        addFoodMoodButton.setForeground(new java.awt.Color(255, 255, 255));
        addFoodMoodButton.setText("Add");
        addFoodMoodButton.setBorderPainted(false);
        addFoodMoodButton.setOpaque(true);
        addFoodMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodMoodButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        newScrollPane.setBorder(null);
        newScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        newScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setLayout(new java.awt.GridBagLayout());
        GridBagConstraints gridFoodMood = new GridBagConstraints();
        gridFoodMood.gridwidth = GridBagConstraints.REMAINDER;
        gridFoodMood.weightx = 1;
        gridFoodMood.weighty = 1;
        backgroundPanel.add(new JPanel(), gridFoodMood);
        newScrollPane.setViewportView(backgroundPanel);

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addFoodMoodButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(moodEnterField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                        .addComponent(foodEnterField, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))))
                            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(newScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel)
                    .addComponent(notificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(foodEnterField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moodEnterField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addFoodMoodButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("FoodMood");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFoodMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodMoodButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Entry created!");
        backgroundPanel.add(createNewJPanel(),createNewJPanelGrid(),0); //creating a new JPanel view
        mmc.writeFoodMoodToFile(foodEnterField.getText(), moodEnterField.getText()); //write the information to a file
        validate();
        repaint();
        //Once operations are done then
        foodEnterField.setText("What you ate");
        moodEnterField.setText("How you feel");        
    }//GEN-LAST:event_addFoodMoodButtonActionPerformed
    
    public String foodTextFieldToString (){
        food = foodEnterField.getText();
        return food;
    }
    
    public String moodTextFieldToString (){
        mood = moodEnterField.getText();
        return mood;
    }
    
    public JPanel createNewJPanel() {
        addANewFoodMood = new FoodMoodCardsPanel(mmc);
        return addANewFoodMood;
    }
    
    public GridBagConstraints createNewJPanelGrid() {
        GridBagConstraints addANewFoodMoodGrid = new GridBagConstraints();
        addANewFoodMoodGrid.gridwidth = GridBagConstraints.REMAINDER;
        addANewFoodMoodGrid.weightx = 1;
        addANewFoodMoodGrid.fill = GridBagConstraints.HORIZONTAL;
        return addANewFoodMoodGrid;
    }

    
    private void moodEnterFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_moodEnterFieldFocusLost
        if(moodEnterField.getText().isEmpty())
        {
            moodEnterField.setText("How you feel");
        }
    }//GEN-LAST:event_moodEnterFieldFocusLost

    private void moodEnterFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_moodEnterFieldFocusGained
        if(moodEnterField.getText().equals("How you feel"))
        {
            moodEnterField.setText("");
        }
    }//GEN-LAST:event_moodEnterFieldFocusGained

    private void foodEnterFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foodEnterFieldFocusLost
        if(foodEnterField.getText().isEmpty())
        {
            foodEnterField.setText("What you ate");
        }
    }//GEN-LAST:event_foodEnterFieldFocusLost

    private void foodEnterFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foodEnterFieldFocusGained
        if(foodEnterField.getText().equals("What you ate"))
        {
            foodEnterField.setText("");
        }
    }//GEN-LAST:event_foodEnterFieldFocusGained

    /**
     * These methods bellow are used to navigate through the application from the
     * MainMenuUI
     * @param evt 
     */
    private void goToRecommButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRecommButtonActionPerformed
        mmc.toRecommendationCntrl();        
    }//GEN-LAST:event_goToRecommButtonActionPerformed

    private void goToChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToChartButtonActionPerformed
        mmc.toStatsCntrl();
    }//GEN-LAST:event_goToChartButtonActionPerformed

    private void notificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsButtonActionPerformed
        mmc.toNotificationCntrl();
    }//GEN-LAST:event_notificationsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFoodMoodButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField foodEnterField;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JButton goToChartButton;
    private javax.swing.JButton goToFoodMoodButton;
    private javax.swing.JButton goToRecommButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JTextField moodEnterField;
    private javax.swing.JScrollPane newScrollPane;
    private javax.swing.JButton notificationsButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewUserButton;
    // End of variables declaration//GEN-END:variables
}
